# metar_remarks.py
# Metar Remark Codes and their definitions - Mark Harris
# dictionary created using;
# https://www.weather.gov/media/wrh/mesowest/metar_decode_key.pdf

metar_remarks = {
    "$": "maintenance check indicator", 
    "-": "light intensity", 
    "+": "heavy intensity", 
    "/": "indicator that visual range data follows; separator between temperature and dew point data.", 
    "ACC": "altocumulus castellanus", 
    "ACFT MSHP": "aircraft mishap", 
    "ACSL": "altocumulus standing lenticular cloud", 
    "AO1": "automated station without precipitation discriminator", 
    "AO2": "automated station with precipitation discriminator", 
    "ALP": "airport location point", 
    "APCH": "approach", 
    "APRNT": "apparent", 
    "APRX": "approximately", 
    "ATCT": "airport traffic control tower", 
    "AUTO": "fully automated report", 
    "B": "began", 
    "BC": "patches", 
    "BKN": "broken", 
    "BL": "blowing", 
    "BR": "mist", 
    "C": "center (with reference to runway designation)", 
    "CA": "cloud-air lightning", 
    "CB": "cumulonimbus cloud", 
    "CBMAM": "cumulonimbus mammatus cloud", 
    "CC": "cloud-cloud lightning", 
    "CCSL": "cirrocumulus standing lenticular cloud", 
    "cd": "candela", 
    "CG": "cloud-ground lightning", 
    "CHI": "cloud-height indicator", 
    "CHINO": "sky condition at secondary location not available", 
    "CIG": "ceiling", 
    "CLR": "clear", 
    "CONS": "continuous", 
    "COR": "correction to a previously disseminated observation", 
    "DOC": "Department of Commerce", 
    "DOD": "Department of Defense", 
    "DOT": "Department of Transportation", 
    "DR": "low drifting", 
    "DS": "duststorm", 
    "DSIPTG": "dissipating", 
    "DSNT": "distant", 
    "DU": "widespread dust", 
    "DVR": "dispatch visual range", 
    "DZ": "drizzle", 
    "E": "east, ended, estimated ceiling (SAO)", 
    "FAA": "Federal Aviation Administration", 
    "FC": "funnel cloud", 
    "FEW": "few clouds", 
    "FG": "fog", 
    "FIBI": "filed but impracticable to transmit", 
    "FIRST": "first observation after a break in coverage at manual station", 
    "FRQ": "frequent", 
    "FROPA": "frontal passage", 
    "FT": "feet", 
    "FU": "smoke", 
    "FZ": "freezing", 
    "FZRANO": "freezing rain sensor not available", 
    "G": "gust", 
    "GR": "hail", 
    "GS": "small hail and/or snow pellets", 
    "HLSTO": "HLSTO hailstone", 
    "HZ": "haze", 
    "IC": "ice crystals, in-cloud lightning", 
    "ICAO": "International Civil Aviation Organization", 
    "INCRG": "increasing", 
    "INTMT": "intermittent", 
    "KT": "KNOTS", 
    "L": "left (with reference to runway designation)", 
    "LAST": "last observation before a break in coverage at a manual station", 
    "LST": "Local Standard Time", 
    "LTG": "lightning", 
    "LWR": "lower", 
    "M": "minus, less than", 
    "max": "maximum", 
    "METAR": "routine weather report provided at fixed intervals", 
    "MI": "shallow", 
    "min": "minimum", 
    "MOV": "moved/moving/movement", 
    "MT": "mountains", 
    "N": "north", 
    "N/A": "not applicable", 
    "NCDC": "National Climatic Data Center", 
    "NE": "northeast", 
    "NOS": "National Ocean Survey", 
    "NOSPECI": "no SPECI reports are taken at the station", 
    "NOTAM": "Notice to Airmen", 
    "NW": "northwest", 
    "NWS": "National Weather Service", 
    "OCNL": "occasional", 
    "OFCM": "Office of the Federal Coordinator for Meteorology", 
    "OHD": "overhead", 
    "OVC": "overcast", 
    "OVR": "over", 
    "P": "indicates greater than the highest reportable value", 
    "PCPN": "precipitation", 
    "PL": "ice pellets", 
    "PK": "peak", 
    "PNO": "precipitation amount not available", 
    "PO": "dust/sand whirls (dust devils)", 
    "PRES": "pressure", 
    "PR": "partial", 
    "PRESFR": "pressure falling rapidly", 
    "PRESRR": "pressure rising rapidly", 
    "PWINO": "precipitation identifier sensor not available", 
    "PY": "spray", 
    "R": "right (with reference to runway designation), runway", 
    "RA": "rain", 
    "RTD": "Routine Delayed (late) observation", 
    "RV": "reportable value", 
    "RVR": "Runway Visual Range", 
    "RVRNO": "RVR system values not available", 
    "RY": "runway", 
    "S": "snow, south", 
    "SA": "sand", 
    "SCSL": "stratocumulus standing lenticular cloud", 
    "SCT": "scattered", 
    "SE": "southeast", 
    "SFC": "surface", 
    "SG": "snow grains", 
    "SH": "shower(s)", 
    "SKC": "sky clear", 
    "SLP": "sea-level pressure", 
    "SLPNO": "sea-level pressure not available", 
    "SM": "statute miles", 
    "SN": "snow",
    "SNB": "snow began",
    "SNE": "snow ended",
    "SNINCR": "snow increasing rapidly", 
    "SP": "snow pellets", 
    "SPECI": "an unscheduled report taken when certain criteria have been met", 
    "SQ": "squalls", 
    "SS": "sandstorm", 
    "STN": "station", 
    "SW": "snow shower, southwest",
    "T": "Hourly temperature and dew point in tenths degrees C",
    "TCU": "towering cumulus", 
    "TS": "thunderstorm", 
    "TSNO": "thunderstorm information not available", 
    "TWR": "tower", 
    "UNKN": "unknown", 
    "UP": "unknown precipitation", 
    "UTC": "Coordinated Universal Time", 
    "V": "variable", 
    "VA": "volcanic ash", 
    "VC": "in the vicinity", 
    "VIS": "visibility", 
    "VISNO": "visibility at secondary location not available", 
    "VR": "visual range", 
    "VRB": "variable", 
    "VV": "vertical visibility", 
    "W": "west", 
    "WG/SO": "Working Group for Surface Observations", 
    "WMO": "World Meteorological Organization", 
    "WND": "wind", 
    "WSHFT": "wind shift", 
    "Z": "Zulu, i.e., Coordinated Universal Time"
}

